interface RateProps {
    id: number,
    timestamp: null,
    metal: string
    currency: string
    exchange: string
    symbol: string
    prevClosePrice: string
    openPrice: string
    lowPrice: string
    highPrice: string
    openTime: null,
    price: string
    ch: string
    chp: string
    ask: string
    bid: string
    priceGram24k: string
    priceGram22k: string
    priceGram21k: string
    priceGram20k: string
    priceGram18k: string
    priceGram14k: string
    priceGram10k: string
    priceBuy: string
    priceSell: string
    createdAt: Date
    updatedAt: Date
}
